AlexeyAB/darknet

- src/utils.c
#270 #325
fix windows format EOL handle.
https://en.wikipedia.org/wiki/Newline
> fix windows format EOL handle

- Makefile
- src/demo.c
Test environment:
- macOS High Sierra 10.13.3
- Xcode 8.3.2
- CUDA 9.1
- cuDNN 7.0.4
> Minor changes to keep MAC OS happy

- README.md
I went through compiling on Windows for the first time; added notes which would have helped.
Please let me know your feedback.
cc: @AlexeyAB and @FaBeyyy since you also went through this recently.
> README.md: add notes to How to compile on Windows

- build/darknet/YoloWrapper.cs
- src/yolo_v2_class.cpp
- src/yolo_v2_class.hpp
I have adjust the array size on c# wrapper, i can't set the size on runtime i removed the not needed method ``max_objects``
> Optimize C# interface adjust array size

- src/yolo_v2_class.cpp
- src/yolo_v2_class.hpp
Add two new methods to get informations about graphic device
> Get gpu count and name

- src/yolo_v2_class.hpp
check image size before resize
> optimize performance - detect method

- src/blas.c
- src/blas.h
- src/blas_kernels.cu
- src/cuda.c
- src/cuda.h
- src/layer.h
- src/parser.c
- src/softmax_layer.c
Classifier now is working for CPU/GPU . 
The file softmax_layer.c was outdated, this fixex https://github.com/AlexeyAB/darknet/issues/1563
> Classifier now is working for CPU/GPU

- net_cam_v3.sh
> Fixed typo in weights file

- Makefile
- src/darknet.c
- src/lstm_layer.c
- src/lstm_layer.h
- src/network.c
- src/parser.c
> add LSTM layer

- src/detector.c
@AlexeyAB please consider merging this. It's a very simple change but feel free to ask questions or make changes.
Closes #2790
> Save weights with best mAP during training

- .travis.yml
- appveyor.yml
- build.sh
- cmake/Modules/FindCUDNN.cmake
improve module after this discussion: https://github.com/AlexeyAB/darknet/commit/09c996f8fb74ade00e50ef03fc6ac06e9235c19c#r34562398
> [cudnn] remove hardcoded version in cmake module

- src/image_opencv.cpp
Looks like a obvious bug to me.
> Fix undefined behavior caused by delete

- README.md
I wasn't sure how to add the distinction without breaking the explanation flow, I hope I did ok...
> Add Gaussian_yolo layer documentation

- src/blas_kernels.cu
- src/classifier.c
- src/detector.c
- src/image_opencv.cpp
- src/image_opencv.h
Display remaining training time on the training chart.
> Monitor training

- include/darknet.h
- src/image.c
- src/network_kernels.cu
fix error quantize_image's result type.
fix warning printf params, in backward_network_gpu.
> fix some errors.

- darknet.py
- include/darknet.h
- src/network.c
- src/yolo_layer.c
- src/yolo_layer.h
Hi @AlexeyAB,
I tried to add batch inference support to the existing code. I tried it on my datasets and I confirm that results are consistent with the single image detection. The only drawback is that batch inference assumes all of the batch images have the same width and height. I'm putting the table that shows the average prediction time per image wrt batch size.
|Batch Size   |Avg. Prediction Time(seconds)   | 
|---|---|
| 1 |  0.065 |
| 2 |  0.060 |
| 3 |  0.056 |
Graphic Processor: GeForce GTX 1050 Ti with Max-Q Design
> Batch inference added

- build.ps1
Fixes #5571
I think I forgot one line :)
> Do not use vcpkg if not found

- src/classifier.c
> Fix a double free error in train_classifier() introduced by a merge

- Makefile
Adds NVCC support for new Ampere GPUs.
Closes #5622
> Add nvcc flag for known Ampere GPUs

- src/classifier.c
> Fix a double free caused by calling free_image() on a shallow copy

- image_yolov4.sh
- net_cam_v4.sh
- video_yolov4.sh
I have added the sample shell scripts for yolov4 to run darknet on an image, video and from a video stream
> Added example  scripts for yolov4

- darknet_video.py
Avoid read and write image at the same time. Fix bug #6897
> Fix bug #6897 OSError: exception: access violation writing  

- src/dark_cuda.c
> Fix no inference detections bug when cudnn is disabled.

- darknet_video.py
Output video in original size and recalculate bbox detection accordingly.
> Fix python video

- CMakeLists.txt
- README.md
- build.ps1
- use parentheses to make clear operator order
- print out versions
- add English language pack requirements in VS as a note to README
- other minor updates
> [build.ps1] improvements

- build.ps1
as per title, found some bugs in some pwsh versions (thanks to discord users 🙏🏻 )
> [urgent] fixes for PowerShell ISE

- .gitignore
- build.ps1
second round of updates and improvements thanks to discord users 🙏🏻
> [build.ps1] download ninja automatically if missing + other small updates

- src/region_layer.c
Not strictly required but it is useful to have sometimes.
> region_layer: Populate out_h/w/c fileds for consitency

- .github/workflows/ccpp.yml
- build.ps1
Add vcpkg port to nightly builds, so that we keep monitor that it stays on track
@AlexeyAB PR is ready for me if badge is green and you don't have any question
> [CI] test vcpkg nightly builds

- include/yolo_v2_class.hpp
- src/yolo_console_dll.cpp
- src/yolo_v2_class.cpp
Add method detectBatch to the C++ API and initialization with custom batch_size
> Add batch inference on C++

- .github/workflows/ccpp.yml
- .github/workflows/on_pr.yml
- README.md
- build.ps1
- scripts/deploy-cuda.ps1
- scripts/deploy-cuda.sh
- scripts/requested_cuda_version.sh
- scripts/setup.ps1
- scripts/setup.sh
> update to cuda 11.5

- README.md
> Update Readme.txt URL Typo

- src/coco.c
- src/detector.c
- src/yolo.c
Fixed memory leaks in "map" code, detected and fix confirmed using valgrind, as described in https://github.com/AlexeyAB/darknet/issues/8308.
> issue #8308: memory leaks in map

- src/parser.c
- src/yolo.c
int -> float in parser.c
https://github.com/AlexeyAB/darknet/issues/8510
Free before using in yolo.c
https://github.com/AlexeyAB/darknet/issues/8511
> Fixed issues 8510 and 8511

- src/detector.c
Closes #8524 
Closes #8158 
Cherry picks relevant commit from stale PR #8158 to close #8524
> - Fix warning -Werror=format-security

- .github/workflows/ccpp.yml
- .github/workflows/on_pr.yml
- build.ps1
- scripts/deploy-cuda.sh
- scripts/setup.ps1
- scripts/setup.sh
- scripts/utils.psm1
> restore Windows PowerShell compatibility

- src/art.c
- src/classifier.c
- src/demo.c
- src/detector.c
replaces #792 which is not necessary anymore since win10 supports ansi escape sequences
> use ansi escape sequence vt100 ESC[H ESC[J to clear screen in a portable way (it's also win10+ supported!)

- Dockerfile.cpu
- Dockerfile.gpu
- docker-compose.yml
> docker fixes

- src/layer.c
> fix memleak

- src/yolo_layer.c
I have corrected the missing 'nbiases' item in the YOLO Layer.
> Fixed Missing 'nbiases' Item in YOLO Layer
