README.md

In the current code it simply saves every 100 iterations. I changed the readme to reflect that.
In detector.c atm:
```
//if (i % 1000 == 0 || (i < 1000 && i % 100 == 0)) {
if (i % 100 == 0) { 
...
```

Fix autosave interval

---

.gitignore
src/yolo_v2_class.cpp
src/yolo_v2_class.hpp

Created alternative implementation for `Tracker_optflow` by leveraging the OpenCV 3.2 or greater `cv::SparsePyrLKOpticalFlow` class which does not depend on CUDA.

CPU implementation of Tracker_optflow

---

build/darknet/x64/darknet.py
darknet.py

Update script to Python 3 compatibility.
Also adds a new function, `performDetect()`, to enable import of this and execution from other scripts. 
An example call from the project I wrote this for:
```python
from skimage import io
from x64.darknet import performDetect
results = performDetect(fullPath, weightPath= "./yolo-obj_27800.weights", makeImageOnly= True)
io.imsave(tmpOutputPath, results["image"])
caption = results["caption"]
```
or as a helper to tag confusing images in sequence:
```python
from x64.darknet import *
import time
performDetect(configPath= configPath, weightPath= weightPath, metaPath= metaPath, initOnly= True)
labelExecuter = ""
labelPath = os.path.abspath(imagesSearchDir + "..\\labels.txt")
if not os.path.exists(labelPath):
print("Warning: couldn't find label path …
```

Python3 detection runner

---

scripts/log_parser/log_parser.py

This allows the script to be run from command line without any errors (for ex, on a remote machine).
This is a follow-up of https://github.com/AlexeyAB/darknet/pull/759

Change matplotlib backend to 'agg' when 'show_plot' is false. 

---

src/box.h
src/convolutional_layer.c
src/darknet.c
src/detector.c
src/image.c
src/image.h

When printing detector results, output was done in random order, obfuscating results for interpreting. Now:
1. Text output includes coordinates of rects in (left,right,top,bottom in pixels) along with label and score
2. Text output is sorted by rect lefts to simplify finding appropriate rects on image
3. If several class probs are above threshold for some detection, the most probable one is written first and coordinates for others are not repeated
4. Rects are imprinted in image in order from low to high probability, so most probable rects are always on top and are not overlayed by less probable ones.
5. Most probable label for rect is always written first
Also:
6. Message about low GPU memory includes required memory size

Output improvements for detector results:

---

build/darknet/x64/darknet.py
darknet.py

darknet.py currently only works when you execute from the same folder.
This PR tries to get rid of this limitation.
Linux might also have the same situation, however I am just focusing on Windows right now.

darknet.py - improve dll loading under Windows

---

src/http_stream.cpp

Fix the compile error of OpenCV 3.4.1 highgui in `http_stream.cpp`

Fix openCV 3.4.1 highgui

---

build/darknet/YoloWrapper.cs

protect internal methods, add exception if openCV support is not available

Optimize YoloWrapper

---

src/image.c

This allows tooling to watch for changes while the application is running.

ext_output: flush stdout after printing output

---

build/darknet/darknet.vcxproj
darknet.py
include/darknet.h
src/convolutional_kernels.cu
src/image.c
src/image.h
src/network.c
src/network.h
src/network_kernels.cu

Three changes.
First one just makes network_predict_image faster in the case that the image and net are the same size.
Second is necessary to support network_predict in python.  This is a bug where python binds to a network* but network_predict was changed at some point to a full copy of the network struct.
Last one allows an image array to be copied from typical RGB format to a darknet image format.  In python, it's currently done with the array_to_image function which I think is actually broken (see commit notes).
With these changes, I'm able to utilize the GPU at nearly native C speeds with a python binding.

Changes to better support python bindings

---

.travis.yml
appveyor.yml
build.ps1
build.sh

I noticed that CUDA was not really built on Windows with the latest revision, this should just make sure that CUDA is really installed and tested.
I also removed the gcc@5 build on macOS, because of the error explained in here: https://github.com/AlexeyAB/darknet/pull/2476
Unfortunately any gcc newer than that was already unsupported, and it seems that on newer OpenCV@3 builds also that gcc went broken. `brew` just went crazy removing all flags for default packages (https://github.com/Homebrew/homebrew-core/issues/31510) but this became in a real mess for me in many works, because it is now impossible to ask for packages with special options or linked with a different stdlib. In this case, the real problem is in fact rooted to a discrepancy between `libc++` and `libstdc++` (clang vs gcc). …

fix cuda build on appveyor, remove old unsupported config on macOS

---

.gitignore
.travis.yml
CMakeLists.txt
DarknetConfig.cmake.in
appveyor.yml
build.ps1
build.sh
cmake/Modules/FindCUDNN.cmake
cmake/Modules/FindDarknet.cmake
cmake/Modules/FindPThreads_windows.cmake
src/darknet.c

In this PR I am preparing the groundwork to enable better integration between `darknet` and a downstream project, using it as a library.
Using the CMake structure already in place, I expanded the target handling and exports, in order to enable an easy `find_package(Darknet)` downstream.
Besides it, I also implemented some tricks to make CI quicker, like splitting the appveyor matrix between debug and release configs, and parallel building whenever possible.
It is not very much tested, so please try it and let me know how is it working for you.
When it will be completed, a `vcpkg` port is ready to be submitted to the official repository (you can try it in my vcpkg fork), to enable "one-click" installation with dependencies and more. 
When this other step will be completed, I will also add …

improve darknet library handling for downstream projects, other small updates

---

src/classifier.c

```
./darknet classifier train data/sort.data cfg/alexnet.cfg -dont_show
alexnet
1
compute_capability = 750, cudnn_half = 1 
layer     filters    size              input                output
0 conv     96 11 x11 / 4   128 x 256 x   3   ->    30 x  62 x  96 0.130 BF
1 max          3 x 3 / 2    30 x  62 x  96   ->    14 x  30 x  96 0.000 BF
2 conv    256  5 x 5 / 1    14 x  30 x  96   ->    14 x  30 x 256 0.516 BF
3 max          3 x 3 / 2    14 x  30 x 256   ->     6 x  14 x 256 0.000 BF
4 conv    384  3 x 3 / 1     6 x  14 x 256   ->     6 x  14 x 384 0.149 BF
5 conv    384  3 x 3 / 1     6 x  14 x 384   ->     6 x  14 x 384 0.223 BF
6 conv    256  3 x 3 / 1     6 x  14 x 384   ->     6 x  14 x 256 0.149 BF
7 max          3 x 3 / 2     6 x  14 x 256   ->     2 x   6 x 256 0.000 BF
8 …
```

Segfault if height > width

---

src/utils.c

This PR adds:
* Support for TIFF images
* Checking that the label file is correctly inferred.
Currently if a non-supported image type is provided (for example tiff), but one that can be opened with e.g. OpenCV, darknet will not correctly replace the extension and it will do this silently. This can result in a fairly subtle bug where training seems to be going OK, loss decreases, but nothing is ever detected. This PR adds a brief message to `stderr` to alert the user.
Probably this function should attempt to replace everything after the last period in the path, rather than relying on a hard-coded list of extensions.

Correctly locate annotation files for tiff images

---

README.md

`steps=` remark for multi-gpu training: should be multiplied as well as `max_batches` & `burn_in`.

Update README.md (steps= for multi-gpu)

---

build.ps1

I have "Visual Studio 2017 Enterprise" edition.
But build.ps1 found no Visual Studio 2017.  (path to Community Edition)
I would like to support the Enterprise edition.

add Visual studio 2017 "Enterprise" edition to edition check.

---

src/detector.c

Doing ./darknet detector map ... now returns precision and recall per class while maintaining the previous global precision and recall

Compute Precision and recall per class

---

include/darknet.h
src/network.c
src/parser.c

I've drafted an implementation of (cosine) stochastic gradient descent with warm restarts: https://arxiv.org/abs/1608.03983
* Adds a user-defined minimum learning rate
* Adds a user-defined cycle length (in batches)
* SGDR is added as a learning rate policy choice:
```c
case SGDR:
rate = net.learning_rate_min + 
0.5*(net.learning_rate-net.learning_rate_min)
* (1. + cos( (float) (batch_num % net.batches_per_cycle)*3.14159265 / net.batches_per_cycle));
return rate;
```
Some thoughts:
* Might be useful to build in learning rate decay - e.g. reduce net.learning_rate_max as with the step policy.
* Could also implement a multiplication factor to increase cycle length over time.
* Would it make more sense to use a cycle length based on epoch rather than batches? 
* Would be interesting to do …

Implement stochastic gradient descent with warm restarts

---

src/yolo_console_dll.cpp

Using `TRACK_OPTFLOW` and `ZED_STEREO` simultaneously results in a segmentation fault :
```
terminate called after throwing an instance of 'cv::Exception'
what():  OpenCV(3.4.6) opencv-3.4.6/modules/cudaimgproc/src/color.cpp:496: error: (-215:Assertion failed) src.channels() == 3 in function 'BGR_to_GRAY'
```
That's because the ZED SDK is outputting RGBA images. This PR adds the OpenCV color conversion to get RGB left images.

Fix cv exception when using both optflow and the ZED

---

CMakeLists.txt

* Fix `nvcc fatal : Unknown option 'fopenmp'` (https://github.com/AlexeyAB/darknet/issues/3314)
* pthread link for 'uselib' missing

Fix Ubuntu cmake compilation

---

src/yolo_layer.c

Hi @AlexeyAB ! I noticed that If you are trying to do batch processing on two images this line of code in yolo_layer.c (ln: 495) will broke any detection. Doesn't make any sense to have  it, right? I would be very gratefull if this is merged since im trying to make batch processing work with the latest version of this repo :) 
` if (l.batch == 2) avg_flipped_yolo(l);`
Thanks in advance

Removed useless snippet that only breaks if batch processing is enabled

---

src/image.c

Function image.c: image resize_image(image im, int w, int h) does full resize procedure even if it is not needed (image has target dimensions already).
This optimization is very useful when images and network dimensions are always equal (e.g training model for specific camera).

Check if image does not require resizing

---

Makefile

The directory must exist before running this rule.  When running `make` with
several parallel jobs it can happen that $(LIBNAMESO) rule is run before
creating the directory.
This is the first PR that we found as part of getting darknet to build with [`BinaryBuilder.jl`](https://github.com/JuliaPackaging/BinaryBuilder.jl) as part of #4323, others will come in the next days.

Add $(OBJDIR) as prerequisite to $(LIBNAMESO)

---

Makefile
src/darkunistd.h
src/gemm.c
src/getopt.h
src/gettimeofday.h

Here are all other patches we applied to cross-compile Darknet for Windows with MinGW in #4323.

Fix compilation for Windows with MinGW

---

Makefile
src/yolo_console_dll.cpp

This PR adds the support of the newly released ZED SDK 3.0 (which introduced breaking changes) while keeping the ZED SDK 2.x compatibility.
Please consider the [`#undef GPU`](https://github.com/AlexeyAB/darknet/compare/master...adujardin:zedsdk_3_support?expand=1#diff-3445cf22867b9f62dcc91c7264e727f6R32). It was necessary to solve the conflict with the new API which includes 'GPU' as an enum value (`sl::MEM::GPU`). This define doesn't seem to be used in the rest of the file, so the scope should be fine and no feature should be impacted, I think.
If you have time to test it, let me know if there's something to change.

Adding support for ZED SDK 3.0 (with 2.8 support maintained)

---

Makefile

I was asked to port https://github.com/pjreddie/darknet/pull/1348 to this repo. These changes allow building with OpenCV 4. The changes are much smaller than in the original darknet repo (https://github.com/pjreddie/darknet/pull/1348/files), since this repo was already avoiding the raw C API.
I tested building with the Makefile only. There might be work to be done on the CMake project.

Support building with OpenCV 4

---

src/yolo_console_dll.cpp

See https://github.com/AlexeyAB/darknet/pull/4762#issuecomment-589726594
It removes the unused `cv_type` from the `slMat2cvMat` function. Only 2 are used, 4C float and 4C uchar for point clouds and color images.

Shorter sl::Mat cast function (Related to #4762)

---

src/yolo_layer.c

If the existing Class_id check is smaller than the value in the cfg file, there is no problem, but if a mistake enters a negative value during the labeling operation, the program terminates without any warning message.
This adds an exception if the Class ID is a garbage value (like negative number).

Class_id Garbage Value Check

---

include/darknet.h
src/classifier.c
src/detector.c
src/image_opencv.cpp
src/image_opencv.h

Hi @AlexeyAB 
I have added -chart argument for nicer charts drawing
If learning stops in the middle, you will get chart like this:
And if you start you learning process again, you will end up with something looking like this:
May be you want to pass your last saved chart to darknet with an argument -chart like this:
```
-chart loss.png
```
and get a chart which will look like this:
I have a friend, who asks me to implement this. Also maybe it will be useful to someone

Added -chart argument

---

src/detector.c

When we redirect output of training into log files, while the net.cudnn_half is True, iteration information line, which contains "avg loss" is missed.
Using \n and fflush() fixed the issue. Each one of them may be enough to fix the issue.

[ fix ] - Not printing Iteration info in log file

---

src/utils.c

I have better performance without omp when I try yolov4 with "uselib". (15 FPS with, 25 without)
Besides, maybe we should replace this code:
https://github.com/AlexeyAB/darknet/blob/e6469eb071521a4ff5be8c0e9cceb524d0a65a95/src/yolo_v2_class.cpp#L304-L309
with this one (as you did for demo.c):
https://github.com/AlexeyAB/darknet/blob/ccafff912bd42728aa873be7b4c7add2366858a8/src/demo.c#L104-L108

Remove omp in mean_arrays

---

.github/workflows/ccpp.yml

Chocolatey installs the latest version by default, but Darknet isn't yet compatible with CUDA 11. Explicitly install the most recent CUDA 10.2 release instead.
Fixes #5959.
Signed-off-by: Juuso Alasuutari <juuso.alasuutari@gmail.com>

Explicitly install CUDA version 10.2 in win-{vcpkg,intlibs}-cuda actions

---

Makefile

space between variable declaration and comment will assign unexpected
value to the variable

fix makefile comment bug

---

src/detector.c

**The aP and mAP were being calculated wrong as mentioned in this issue:** [link](https://github.com/AlexeyAB/darknet/issues/6040)
I have added code to calculate and add the area of part of AUC (under PR) which was not being added in the case when the recall was non-zero for the Rank-1 detection.(mainly seen in test set with less images.) 
**So the area of curve between the: rank-1 detection with non-zero recall and point with zero recall is now calculated.** which wasn't being calculated earlier.
To check the problem and reason of that problem....check the issue where I have explained all in detail with proof. [link](https://github.com/AlexeyAB/darknet/issues/6040)

Fixed incorrect calculation of mAP for -points 0 (for own dataset) issue #6040

---

include/yolo_v2_class.hpp
src/yolo_console_dll.cpp

Clears "-Wreorder" build warnings.
Signed-off-by: Juuso Alasuutari <juuso.alasuutari@gmail.com>

Fix member initialization ordering

---

src/gemm.c
src/im2col_kernels.cu
src/yolo_layer.c

This change silences a compiler warning emitted by gcc with `-Wall`. It also works around a highlighting issue which is caused by broken comment syntax parsing in at least one editor[1].
No functional changes.
[1] https://imgur.com/a/YA5WCtx
Signed-off-by: Juuso Alasuutari <juuso.alasuutari@gmail.com>

Fix '"/*" within comment' warnings; remove instances of '//*'

---

include/darknet.h
src/network.c

Added method to free network from C# environment using network pointer instead of network object.
`LIB_API void free_network_ptr(network* net);`

Minor addition

---

darknet.py
darknet_images.py
darknet_video.py

First of all, thank for this well maintained repo, and kudos for the YOLOv4 step and its paper. It was written in a very instructive way.
Many useful features implemented in darknet C code are not accessed by the python wrapper, and the ones that can be used haven't the same commands. At the end, this situation becomes in a switching between both languages, and some incompatibilities with python MLOps tools.
* Added **colors for bboxes**, one for each class.
* Added **command parser**.  At the moment, parameters for python scripts are handcoded. With this parser, we can invoke darknet like the README documentation:
```
python darknet_video.py --data_file cfg/coco.data --config_file cfg/yolov4.cfg --weights yolov4.weights --thresh 0.7 --input test.mp4 
```
* Print **bbox coordinates** with …

Giving python wrapper almost same functionalities and interface as C code

---

darknet.py

```python
import os
import sys
os.environ['DARKNET_PATH'] = '/usr/local/darknet'
sys.path.append(os.environ['DARKNET_PATH'])
import darknet
def main():
network, class_names, class_colors = darknet.load_network(
'../nscan-train/data/cfg/yolov4-tiny-3l-numbers-12.cfg',
'../nscan-train/data/numbers.data',
'./data/weights/numbers/yolov4-tiny-3l-numbers-12_last.weights',
batch_size=1
)
if __name__ == '__main__':
main()
```

Update darknet.py to run outside the darknet folder

---

darknet.py

Hi @AlexeyAB ,
In the use cases of running darknet for inference in Python environment, especially in Kaggle GPU notebooks, it is essential to get the flexibility of freeing CUDA memory from the loaded darknet models while generating ensembles.
I noticed that there has been a `free_network_ptr` function defined in the darknet C code that can be utilized to avoid CUDA out-of-memory issues.
Here is a PR to merge this part of support into `darknet.py` that I've already tested it on [a Kaggle GPU notebook](https://www.kaggle.com/markpeng/yolov4-infer-gpu-v3-tta-fold2-pseudo-label-final/data?scriptVersionId=40120067), thanks!

Add free_network_ptr Support for Darknet in Python

---

src/network.c
src/utils.c

We use darknet at Observa in a production environment and these couple of changes improve model loading performance by around 0.9 seconds.
Changes
- Move part of a large multiplication outside of innermost loop in `fuse_conv_batchnorm`
- Remove unnecessary memset(0) after calloc in `xcalloc`

Improve model loading performance for detect

---

darknet_images.py
darknet_video.py

Hi:
I tested the python API and the memory leak was fast growing, and I checked the darknet.py where I found free_image(), according IMAGE structure, I added the free function after detect_image() to free IMAGE from make_image, and everything was fine!
Thx,
A.H.

Fix: Python example API that caused Memory leak.

---

src/gemm.c

Fix problems with Xcode 12 on macOS
```
darknet/src/gemm.c:549:21: fatal error: redefinition of '_castu32_f32'
static inline float _castu32_f32(uint32_t a) {
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/ia32intrin.h:243:1: note: 
previous definition is here
_castu32_f32(unsigned int __A) {
```
Proper fix would be using the intrinsics defined by the compilers, but since we were already using custom ones, refactoring the name was the preferred solution

fix compatibility with newer clang

---

Makefile
README.md

Not sure if this is necessary may help others installing #6942 
Background:
With CUDA 11 the support for Kepler GPU is dropped. 
Therefore if you add the flag `-gencode arch=compute_30,code=sm_30` nvcc will fail

Added a hint for installation with CUDA version >= 11

---

src/activation_kernels.cu
src/blas_kernels.cu
src/convolutional_kernels.cu

This should unify our Cuda Math function calls (for float). And fix the Windows build errors reported in #7457, #7472, #7498.

Cuda: floor -> floorf, ceil -> ceilf

---

src/batchnorm_layer.c

Fix memory error in batchnorm layer when running darknet as CPU mode

fix memory error in batchnorm layer

---

darknet_images.py

Solves an issue in darknet_images.py that arrises when trying to label images provided through a relative path to a folder that starts with a dot or that has hidden folders inside the path.
run the following command:
`python3 darknet_images.py --input ./IMAGES --weights /path/to/weights --config_file /path/to/cfg --data_file path/to/data  --save_labels`
Instead of generating a .txt for each image, it generates a single file at $PWD/.txt.

Fixed relative paths in darknet_images.py

---

src/demo.c
src/image_opencv.cpp
src/image_opencv.h
src/utils.c
src/utils.h

when use low-performance devices such as raspberry pi or jetson nano execute darknet demo, the streaming will be delayed more and more. Therefore, the darknet process need to consume frames from the image capture every time to ensure that the next frame is the latest

fix: frame delay

---

.github/workflows/ccpp.yml
build.ps1

I might have found what failed on your system @AlexeyAB . I tried build.ps1 script only on PowerShell v6 and v7, on v5 it was failing.
Is it better now? Can you please test the script as before?

add support for Windows PowerShell

---

src/parser.c

I wrote a code in python that automatically zip the weights file immediately when using darknet complete training, but I found that the file is not complete.

fix: flush buffer to weights-file when writing each layer

---

.github/workflows/ccpp.yml
.github/workflows/on_pr.yml
.github/workflows/rebase.yml
build.ps1
src/csharp/CMakeLists.txt
src/csharp/YoloCSharpWrapper.cs

in this way, we will be able to just write `/rebase` in a comment in a PR and automatically the PR will be rebased on the newest darknet master branch. This will be very useful to reconsider old Pull Requests which are old and untested with recent modifications
To trigger automatic rebuild we would need to add a personal access token to the repository. We can consider that, or just remember that opening and closing the PR will just trigger a rebuild (see https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250/37 for more details)

add automatic rebase github action

---

darknet_video.py

I found darknet_video.py don't save output video correctly and fixed 2 bugs.
1. cv2.VideoWriter frame size
cv2.VideoWriter frame size must be original video size (not resized image size).
2. converting rgb to bgr
A image is already bgr.

Fix bugs in darknet_video.py

---

src/detector.c

This is needed when you want to achieve a specific precision/recall operating point, you need to know the probability at that point when running inference. I originally called it `threshold`, but thought that had been used in many places, so went with `prob`.

Adds probability to precision recall curve

---

include/darknet.h
src/detector.c

This PR adds support for mAP calculation with user-specified thresholds in training as when `detector map`.

add support for mAP calculation with user-specified thresholds in training

---

darknet.py
include/darknet.h
src/network.c

If you look at remove_negatives in darknet.py, it gives you the final detections for an image after going through a nested loop. The outer loop iterates through all the output detection objects given by the neural net and then the inner loop iterates through all the class names (since one of the outputs of the neural net is an array of probabilities whose size is equal to the number of all classes). This is not much of an issue if you have just 80 class names (the original COCO). But, with YOLO9000, you have 9418 class names. So, iterating through almost 9k names for each detection object causes a significant slowdown.
In network.c, I keep track of the class index that gives the highest probability value. Then, in remove_negatives_faster, instead of iterating through all class indices …

Made inference faster (this is especially useful when using Yolo9000)

---

.github/workflows/ccpp.yml
.github/workflows/on_pr.yml
CMakeLists.txt
build.ps1

saves time and avoid failures due to full storage on GitHub Actions Runners

[CI] build dependencies in release-only mode

---

darknet_images.py

I'm doing some refactoring of The Spaghetti Detective, a service that uses YOLO to detect images of 3d printer "spaghetti" and stop the printer when it's failing (details at https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/issues/552).
I'd like to eliminate some old code there and rely on `darknet_images.py` in this repo, but we receive the image via URL and don't have a file to load in. Rather than writing it to a tmpdir and reading it back in again, I'd prefer to pass the image directly, which is possible with this PR.
I also removed a duplicate import - `darknet` is imported twice (line 5 and line 8 of the original) which caused a weird error.

Allow passing image to image_detection()

---

package.xml

This pull request allows this repository to be used directly with the popular [**robotics middleware ROS**](https://www.ros.org/) by providing a **manifest** `package.xml`, a simple text file containing its dependencies, that is compatible with [ROS](http://wiki.ros.org/catkin/package.xml) as well as [ROS 2](https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.html). Previously this was only possible through wrappers such as [`darknet_ros`](https://github.com/leggedrobotics/darknet_ros) or [`darknet_vendor`](https://github.com/ros2/darknet_vendor) that use [the initial Darknet](https://github.com/pjreddie/darknet) which is no longer actively maintained. This is related to previous issue https://github.com/AlexeyAB/darknet/issues/5457.
This change makes …

Allow repository to be used with ROS/ROS 2

---

include/darknet.h
src/network.h

I have just updated a [ROS 2 package that uses Darknet](
https://github.com/ros2/openrobotics_darknet_ros/) to work with its latest version, [Humble](https://docs.ros.org/en/humble/index.html). Previously it was using [Joseph Redmon's original version of Darknet](https://github.com/pjreddie/darknet) and was using the **`set_batch_network`** function which in this version is not part of the **public API**. This pull request simply exposes this function and as such is related to https://github.com/AlexeyAB/darknet/issues/2956, https://github.com/AlexeyAB/darknet/issues/3924 and the corresponding pull request https://github.com/AlexeyAB/darknet/pull/3465.

Move set_batch_network to public API

---

build/darknet/yolo_cpp_dll_no_gpu.vcxproj

Source file was missing from project (there already is an issue: #8529).
The fact that noone else noticed makes me wonder:
1. Is this project still used / maintained / supported ?
2. Are any of the *.vcxproj*s still used / maintained / supported?
If the answer to the questions is "yes", would it make sense to make further improvements to them?

Fix yolo_cpp_dll_no_gpu.vcxproj build failure

---

src/utils.c

Fix a bug when filename contains multiple extension, the bbox .txt filename cannot be generated.

Support label image filename with multiple extension.
